### PR TITLE
Test pull-request hook

### PR DESCRIPTION
**Pull request by Ghostbird**

### CODE REVIEW

**Comment by Ghostbird** [comment]
Test

**Comment by StephanMeijer** [comment]
And does it work?

**Comment by Ghostbird** [comment]
No, and it turned into a bloody mess.

**Comment by Hallfaer** [comment]
**pylint results:**

```
************* Module plws.github_webhook_server
W: 18, 0: TODO: authentication (fixme)
C: 29, 0: Line too long (103/100) (line-too-long)
C: 48, 0: Line too long (139/100) (line-too-long)
C:  1, 0: Missing module docstring (missing-docstring)
C: 11, 0: Invalid constant name "config" (invalid-name)
C: 13, 0: Missing class docstring (missing-docstring)
C: 14, 4: Invalid method name "do_POST" (invalid-name)
C: 14, 4: Missing method docstring (missing-docstring)
W: 39, 8: No exception type(s) specified (bare-except)
C: 24,48: More than one statement on a single line (multiple-statements)
E: 33,22: Too many positional arguments for constructor call (too-many-function-args)
E: 36,19: Instance of 'GitHandler' has no 'getPath' member (no-member)
C: 42, 4: Invalid method name "__githubRespond" (invalid-name)
R: 42, 4: Method could be a function (no-self-use)
W:  3, 0: Unused import urllib (unused-import)
C:  3, 0: standard import "import urllib" comes before "from github import Github" (wrong-import-order)
C:  4, 0: standard import "import json" comes before "from github import Github" (wrong-import-order)
C:  5, 0: standard import "import os" comes before "from github import Github" (wrong-import-order)
C:  6, 0: standard import "import shutil" comes before "from github import Github" (wrong-import-order)
************* Module plws.git_handler
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: Missing class docstring (missing-docstring)
C: 12, 4: Missing method docstring (missing-docstring)
C: 24, 4: Invalid method name "__getTempFolder" (invalid-name)
R: 24, 4: Method could be a function (no-self-use)
C: 30, 4: Invalid method name "getPath" (invalid-name)
C: 30, 4: Missing method docstring (missing-docstring)
C: 30,23: More than one statement on a single line (multiple-statements)
C:  2, 0: standard import "import os" comes before "from git import Repo, Git" (wrong-import-order)
C:  3, 0: standard import "import tempfile" comes before "from git import Repo, Git" (wrong-import-order)
************* Module plws.__main__
C:  1, 0: Missing module docstring (missing-docstring)
C: 10, 0: Invalid constant name "config" (invalid-name)
C: 12, 0: Invalid constant name "hostName" (invalid-name)
C: 13, 0: Invalid constant name "hostPort" (invalid-name)
C: 15, 0: Invalid constant name "server" (invalid-name)
W:  5, 0: Unused parse_qs imported from urllib.parse (unused-import)
W:  6, 0: Unused parse_header imported from cgi (unused-import)
W:  6, 0: Unused parse_multipart imported from cgi (unused-import)
************* Module plws.pylint_runner
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing class docstring (missing-docstring)
C:  7, 4: Invalid argument name "st" (invalid-name)
C:  7, 4: Missing method docstring (missing-docstring)
C:  9, 4: Missing method docstring (missing-docstring)
C: 12, 0: Missing function docstring (missing-docstring)


Report
======
87 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |5      |5          |=          |20.00       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |3      |3          |=          |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|method   |9      |9          |=          |44.44       |44.44    |
+---------+-------+-----------+-----------+------------+---------+
|function |1      |1          |=          |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+



External dependencies
---------------------
::

    git (plws.git_handler)
    git_handler (plws.github_webhook_server)
    github (plws.github_webhook_server)
    github_webhook_server (plws.__main__)
    pylint 
      \-lint (plws.pylint_runner)
      \-reporters 
        \-text (plws.pylint_runner)
    pylint_runner (plws.github_webhook_server)



Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |93     |72.09 |93       |=          |
+----------+-------+------+---------+-----------+
|docstring |0      |0.00  |0        |=          |
+----------+-------+------+---------+-----------+
|comment   |1      |0.78  |1        |=          |
+----------+-------+------+---------+-----------+
|empty     |35     |27.13 |35       |=          |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |0        |=          |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |0.000    |=          |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |33     |33       |=          |
+-----------+-------+---------+-----------+
|refactor   |2      |2        |=          |
+-----------+-------+---------+-----------+
|warning    |6      |6        |=          |
+-----------+-------+---------+-----------+
|error      |2      |2        |=          |
+-----------+-------+---------+-----------+



% errors / warnings by module
-----------------------------

+---------------------------+-------+--------+---------+-----------+
|module                     |error  |warning |refactor |convention |
+===========================+=======+========+=========+===========+
|plws.github_webhook_server |100.00 |50.00   |50.00    |39.39      |
+---------------------------+-------+--------+---------+-----------+
|plws.__main__              |0.00   |50.00   |0.00     |15.15      |
+---------------------------+-------+--------+---------+-----------+
|plws.git_handler           |0.00   |0.00    |50.00    |27.27      |
+---------------------------+-------+--------+---------+-----------+
|plws.pylint_runner         |0.00   |0.00    |0.00     |18.18      |
+---------------------------+-------+--------+---------+-----------+



Messages
--------

+-----------------------+------------+
|message id             |occurrences |
+=======================+============+
|missing-docstring      |13          |
+-----------------------+------------+
|invalid-name           |10          |
+-----------------------+------------+
|wrong-import-order     |6           |
+-----------------------+------------+
|unused-import          |4           |
+-----------------------+------------+
|no-self-use            |2           |
+-----------------------+------------+
|multiple-statements    |2           |
+-----------------------+------------+
|line-too-long          |2           |
+-----------------------+------------+
|too-many-function-args |1           |
+-----------------------+------------+
|no-member              |1           |
+-----------------------+------------+
|fixme                  |1           |
+-----------------------+------------+
|bare-except            |1           |
+-----------------------+------------+



Global evaluation
-----------------
Your code has been rated at 4.14/10 (previous run: 4.14/10, +0.00)


```

**Comment by Ghostbird** [comment]
Woo! It works again!

**Comment by Hallfaer** [comment]
**pylint results:**

```
************* Module plws.github_webhook_server
W: 18, 0: TODO: authentication (fixme)
C: 29, 0: Line too long (103/100) (line-too-long)
C: 48, 0: Line too long (139/100) (line-too-long)
C:  1, 0: Missing module docstring (missing-docstring)
C: 11, 0: Invalid constant name "config" (invalid-name)
C: 13, 0: Missing class docstring (missing-docstring)
C: 14, 4: Invalid method name "do_POST" (invalid-name)
C: 14, 4: Missing method docstring (missing-docstring)
W: 39, 8: No exception type(s) specified (bare-except)
C: 24,48: More than one statement on a single line (multiple-statements)
E: 33,22: Too many positional arguments for constructor call (too-many-function-args)
E: 36,19: Instance of 'GitHandler' has no 'getPath' member (no-member)
C: 42, 4: Invalid method name "__githubRespond" (invalid-name)
R: 42, 4: Method could be a function (no-self-use)
W:  3, 0: Unused import urllib (unused-import)
C:  3, 0: standard import "import urllib" comes before "from github import Github" (wrong-import-order)
C:  4, 0: standard import "import json" comes before "from github import Github" (wrong-import-order)
C:  5, 0: standard import "import os" comes before "from github import Github" (wrong-import-order)
C:  6, 0: standard import "import shutil" comes before "from github import Github" (wrong-import-order)
************* Module plws.git_handler
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: Missing class docstring (missing-docstring)
C: 12, 4: Missing method docstring (missing-docstring)
C: 24, 4: Invalid method name "__getTempFolder" (invalid-name)
R: 24, 4: Method could be a function (no-self-use)
C: 30, 4: Invalid method name "getPath" (invalid-name)
C: 30, 4: Missing method docstring (missing-docstring)
C: 30,23: More than one statement on a single line (multiple-statements)
C:  2, 0: standard import "import os" comes before "from git import Repo, Git" (wrong-import-order)
C:  3, 0: standard import "import tempfile" comes before "from git import Repo, Git" (wrong-import-order)
************* Module plws.__main__
C:  1, 0: Missing module docstring (missing-docstring)
C: 10, 0: Invalid constant name "config" (invalid-name)
C: 12, 0: Invalid constant name "hostName" (invalid-name)
C: 13, 0: Invalid constant name "hostPort" (invalid-name)
C: 15, 0: Invalid constant name "server" (invalid-name)
W:  5, 0: Unused parse_qs imported from urllib.parse (unused-import)
W:  6, 0: Unused parse_header imported from cgi (unused-import)
W:  6, 0: Unused parse_multipart imported from cgi (unused-import)
************* Module plws.pylint_runner
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing class docstring (missing-docstring)
C:  7, 4: Invalid argument name "st" (invalid-name)
C:  7, 4: Missing method docstring (missing-docstring)
C:  9, 4: Missing method docstring (missing-docstring)
C: 12, 0: Missing function docstring (missing-docstring)


Report
======
87 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |5      |5          |=          |20.00       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |3      |3          |=          |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|method   |9      |9          |=          |44.44       |44.44    |
+---------+-------+-----------+-----------+------------+---------+
|function |1      |1          |=          |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+



External dependencies
---------------------
::

    git (plws.git_handler)
    git_handler (plws.github_webhook_server)
    github (plws.github_webhook_server)
    github_webhook_server (plws.__main__)
    pylint 
      \-lint (plws.pylint_runner)
      \-reporters 
        \-text (plws.pylint_runner)
    pylint_runner (plws.github_webhook_server)



Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |93     |72.09 |93       |=          |
+----------+-------+------+---------+-----------+
|docstring |0      |0.00  |0        |=          |
+----------+-------+------+---------+-----------+
|comment   |1      |0.78  |1        |=          |
+----------+-------+------+---------+-----------+
|empty     |35     |27.13 |35       |=          |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |0        |=          |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |0.000    |=          |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |33     |33       |=          |
+-----------+-------+---------+-----------+
|refactor   |2      |2        |=          |
+-----------+-------+---------+-----------+
|warning    |6      |6        |=          |
+-----------+-------+---------+-----------+
|error      |2      |2        |=          |
+-----------+-------+---------+-----------+



% errors / warnings by module
-----------------------------

+---------------------------+-------+--------+---------+-----------+
|module                     |error  |warning |refactor |convention |
+===========================+=======+========+=========+===========+
|plws.github_webhook_server |100.00 |50.00   |50.00    |39.39      |
+---------------------------+-------+--------+---------+-----------+
|plws.__main__              |0.00   |50.00   |0.00     |15.15      |
+---------------------------+-------+--------+---------+-----------+
|plws.git_handler           |0.00   |0.00    |50.00    |27.27      |
+---------------------------+-------+--------+---------+-----------+
|plws.pylint_runner         |0.00   |0.00    |0.00     |18.18      |
+---------------------------+-------+--------+---------+-----------+



Messages
--------

+-----------------------+------------+
|message id             |occurrences |
+=======================+============+
|missing-docstring      |13          |
+-----------------------+------------+
|invalid-name           |10          |
+-----------------------+------------+
|wrong-import-order     |6           |
+-----------------------+------------+
|unused-import          |4           |
+-----------------------+------------+
|no-self-use            |2           |
+-----------------------+------------+
|multiple-statements    |2           |
+-----------------------+------------+
|line-too-long          |2           |
+-----------------------+------------+
|too-many-function-args |1           |
+-----------------------+------------+
|no-member              |1           |
+-----------------------+------------+
|fixme                  |1           |
+-----------------------+------------+
|bare-except            |1           |
+-----------------------+------------+



Global evaluation
-----------------
Your code has been rated at 4.14/10 (previous run: 4.14/10, +0.00)


```

**Comment by StephanMeijer** [comment]
Nice job

**Pull request closed without merging**
